import lean.KgSchrodinger
import lean.KleinGordonWave
import lean.StiffString
import lean.TelegraphDiffusion
import lean.TelegraphWave
import lean.Pendulum
import lean.KgOscillator
import lean.OscillatorDictionary
import lean.WaveDalembert
import lean.Eddington
import lean.YangMills
import lean.JohnsonNyquist
import lean.Mond
import lean.Einstein
import lean.VacuumFriedmann
import lean.Dimensional
import lean.Coarsening
import lean.KibbleZurek
import lean.HawkingUnruh
import lean.Fret
import lean.QuantumBounce
import lean.Landauer
import lean.Jarzynski
import lean.Lindblad
import lean.Jeans
import lean.Deflection
import lean.Sommerfeld
import lean.ThermalDeBroglie
import lean.Josephson
import lean.QuantumHall
import lean.Laughlin
import lean.Kss
import lean.PlanckArea
import lean.Shapiro
import lean.RandallSundrum
import lean.EinsteinCartan
import lean.EffectiveTemperature
import lean.ToricCode
import lean.QuantumCritical
import lean.TimeSymmetric
import lean.BornOverlap
import lean.EntropyProduction
import lean.CompositeHiggs
import lean.Crossing
import lean.Chandrasekhar
import lean.Entanglement
import lean.RadiationPressure
import lean.AlfvenSpeed
import lean.TolmanEhrenfest
import lean.FastMagnetosonic
import lean.EinsteinRelation
import lean.Clapeyron
import lean.GravitationalRedshift
import lean.KelvinRelation
import lean.MagneticPressure
import lean.LondonPenetration
import lean.PlasmaBeta
