import lean.KgSchrodinger
import lean.KleinGordonWave
import lean.StiffString
import lean.TelegraphDiffusion
import lean.TelegraphWave
import lean.Pendulum
import lean.KgOscillator
import lean.OscillatorDictionary
import lean.WaveDalembert
import lean.Eddington
import lean.YangMills
import lean.JohnsonNyquist
import lean.Mond
import lean.Einstein
import lean.VacuumFriedmann
import lean.Dimensional
import lean.Coarsening
import lean.KibbleZurek
import lean.HawkingUnruh
import lean.Fret
import lean.QuantumBounce
import lean.Landauer
import lean.Jarzynski
import lean.Lindblad
import lean.Jeans
import lean.Deflection
import lean.Sommerfeld
import lean.ThermalDeBroglie
import lean.Josephson
import lean.QuantumHall
import lean.Laughlin
import lean.Kss
import lean.PlanckArea
import lean.Shapiro
import lean.RandallSundrum
import lean.EinsteinCartan
import lean.EffectiveTemperature
import lean.ToricCode
import lean.QuantumCritical
import lean.TimeSymmetric
import lean.BornOverlap
import lean.EntropyProduction
import lean.CompositeHiggs
import lean.Crossing
import lean.Chandrasekhar
import lean.Entanglement
import lean.RadiationPressure
import lean.AlfvenSpeed
import lean.TolmanEhrenfest
import lean.FastMagnetosonic
import lean.EinsteinRelation
import lean.Clapeyron
import lean.GravitationalRedshift
import lean.KelvinRelation
import lean.MagneticPressure
import lean.LondonPenetration
import lean.PlasmaBeta
import lean.HagenPoiseuille
import lean.EulerBuckling
import lean.PullIn
import lean.MottGurney
import lean.ChildLangmuir
import lean.ShockleyDiode
import lean.Thomson
import lean.FourPoint
import lean.ShotNoise
import lean.ReynoldsAnalogy
import lean.CapacitorNoise
import lean.FermiSea
import lean.DebyeCutoff
import lean.DebyeHeat
import lean.EinsteinSolid
import lean.SommerfeldHeat
import lean.CurieWeiss
import lean.PauliParamagnetism
import lean.GinzburgLandau
import lean.UpperCritical
import lean.AmbegaokarBaratoff
import lean.BcsJump
import lean.MassAction
import lean.LyddaneSachsTeller
import lean.BktJump
import lean.LandauerConductance
