import lean.KgSchrodinger
import lean.KleinGordonWave
import lean.StiffString
import lean.TelegraphDiffusion
import lean.TelegraphWave
import lean.Pendulum
import lean.KgOscillator
import lean.OscillatorDictionary
import lean.WaveDalembert
import lean.Eddington
import lean.YangMills
import lean.JohnsonNyquist
import lean.Mond
import lean.Einstein
import lean.VacuumFriedmann
import lean.Dimensional
import lean.Coarsening
import lean.KibbleZurek
import lean.HawkingUnruh
import lean.Fret
import lean.QuantumBounce
import lean.Landauer
import lean.Jarzynski
import lean.Lindblad
import lean.Jeans
import lean.Deflection
import lean.Sommerfeld
import lean.ThermalDeBroglie
import lean.Josephson
import lean.QuantumHall
import lean.Laughlin
import lean.Kss
import lean.PlanckArea
import lean.Shapiro
import lean.RandallSundrum
import lean.EinsteinCartan
import lean.EffectiveTemperature
import lean.ToricCode
import lean.QuantumCritical
import lean.TimeSymmetric
import lean.BornOverlap
import lean.EntropyProduction
import lean.CompositeHiggs
import lean.Crossing
import lean.Chandrasekhar
import lean.Entanglement
import lean.RadiationPressure
import lean.AlfvenSpeed
import lean.TolmanEhrenfest
import lean.FastMagnetosonic
import lean.EinsteinRelation
import lean.Clapeyron
import lean.GravitationalRedshift
import lean.KelvinRelation
import lean.MagneticPressure
import lean.LondonPenetration
import lean.PlasmaBeta
import lean.HagenPoiseuille
import lean.EulerBuckling
import lean.PullIn
import lean.MottGurney
import lean.ChildLangmuir
import lean.ShockleyDiode
import lean.Thomson
import lean.FourPoint
import lean.ShotNoise
import lean.ReynoldsAnalogy
import lean.CapacitorNoise
import lean.CombDrive
import lean.SubthresholdSwing
import lean.BoostConverter
import lean.FinEfficiency
import lean.ThermoelectricGenerator
import lean.Joukowsky
import lean.CoaxialCapacitance
import lean.DampingRatio
import lean.FermiSea
import lean.DebyeCutoff
import lean.DebyeHeat
import lean.EinsteinSolid
import lean.SommerfeldHeat
import lean.CurieWeiss
import lean.PauliParamagnetism
import lean.GinzburgLandau
import lean.UpperCritical
import lean.AmbegaokarBaratoff
import lean.BcsJump
import lean.MassAction
import lean.LyddaneSachsTeller
import lean.BktJump
import lean.LandauerConductance
import lean.BohmSheath
import lean.IonAcoustic
import lean.UpperHybrid
import lean.ColdPlasmaCutoff
import lean.LowerHybrid
import lean.ObliqueMagnetosonic
import lean.BennettPinch
import lean.LossCone
import lean.GradBDrift
import lean.ExBDrift
import lean.LandauDamping
import lean.DebyeSphere
import lean.MultiDebye
import lean.LorentzResistivity
import lean.ResistiveSlab
import lean.ParkerCritical
import lean.ParkerSpiral
import lean.ChapmanFerraro
import lean.LawsonBreakeven
import lean.LangmuirProbe
import lean.CrossFieldDiffusion
import lean.Firehose
import lean.MirrorInstability
import lean.AcDrude
import lean.BlochLaw
import lean.BuiltinVoltage
import lean.DensityOfStates2D
import lean.DensityOfStates3D
import lean.GorterCasimir
import lean.JosephsonInductance
import lean.LowerCritical
import lean.Matthiessen
import lean.OnsagerFrequency
import lean.SemiconductorFermi
import lean.Stoner
import lean.ThomasFermi
import lean.Arrhenius
import lean.Eyring
import lean.GibbsIsotherm
import lean.VanTHoff
import lean.NernstGibbs
import lean.ClausiusClapeyron
import lean.Raoult
import lean.Prandtl
import lean.ReynoldsNumber
import lean.Biot
import lean.Nusselt
import lean.Schmidt
import lean.Sherwood
import lean.FourierConduction
import lean.NewtonCooling
import lean.Otto
import lean.JouleThomson
import lean.PlanckSpectrum
import lean.StefanBoltzmann
import lean.WienDisplacement
import lean.SackurTetrode
import lean.Saha
import lean.RichardsonDushman
import lean.OnsagerReciprocity
import lean.CantileverStiffness
import lean.CantileverFrequency
import lean.SpringSoftening
import lean.QuarterBridge
import lean.CoaxialImpedance
import lean.SauerbreyMass
import lean.EquipartitionDisplacement
import lean.ThermomechanicalNoise
import lean.BolometerNep
import lean.PeltierMaxDeltaT
import lean.HarvesterPower
import lean.MeanFreePath
import lean.BlochOscillation
import lean.PippardCoherence
import lean.ClausiusMossotti
import lean.DepairingCurrent
import lean.SchottkyMott
import lean.WannierExciton
import lean.ChargingEnergy
import lean.WeakLocalization
import lean.ThermalConductanceQuantum
import lean.KondoTemperature
import lean.SweetParker
import lean.SedovTaylor
import lean.StrongShock
import lean.BohmDiffusion
import lean.BondiHoyle
import lean.Stromgren
import lean.DispersionDelay
import lean.FaradayRotation
import lean.LarmorRadiation
import lean.Bremsstrahlung
import lean.CriticalIonization
import lean.LmtdCounterflow
import lean.EpsilonNtu
import lean.BlasiusFriction
import lean.ErgunEquation
import lean.BraytonCycle
import lean.LangmuirIsotherm
import lean.ButlerVolmer
import lean.DebyeHuckel
import lean.KelvinDroplet
import lean.GasMeanFreePath
import lean.GrayBodyExchange
import lean.NernstEinsteinConductivity
import lean.SchwarzschildCircularOrbits
import lean.BinaryGWPower
import lean.PetersInspiralTime
import lean.GeodeticPrecession
import lean.MatterDominatedAge
import lean.HillRadius
import lean.BekensteinBound
import lean.PhotonGasEnergyDensity
import lean.EtheringtonReciprocity
import lean.SynchrotronCoolingTime
import lean.PulsarSpinDownField
import lean.FresnelNormal
import lean.RayleighCriterion
import lean.AbbeResolution
import lean.GaussianBeam
import lean.FabryPerot
import lean.Etendue
import lean.SchawlowTownes
import lean.LaserThreshold
import lean.PhotodiodeResponsivity
import lean.PhotonicBandGap
import lean.PockelsHalfWave
import lean.DopplerWidth
import lean.ElasticWaveSpeeds
import lean.ModuliRelation
import lean.ImpedanceReflection
import lean.StokesKirchhoff
import lean.HelmholtzResonator
import lean.MachAngle
import lean.MinnaertResonance
import lean.ZenerDamping
import lean.PiezoCoupling
import lean.BrillouinShift
import lean.PhotoacousticPressure
