import PhysJS.KgSchrodinger
import PhysJS.KleinGordonWave
import PhysJS.StiffString
import PhysJS.TelegraphDiffusion
import PhysJS.TelegraphWave
import PhysJS.Pendulum
import PhysJS.KgOscillator
import PhysJS.OscillatorDictionary
import PhysJS.WaveDalembert
import PhysJS.Eddington
import PhysJS.YangMills
import PhysJS.JohnsonNyquist
import PhysJS.Mond
