import PhysJS.KgSchrodinger
import PhysJS.KleinGordonWave
import PhysJS.StiffString
import PhysJS.TelegraphDiffusion
import PhysJS.TelegraphWave
import PhysJS.Pendulum
import PhysJS.KgOscillator
import PhysJS.OscillatorDictionary
import PhysJS.WaveDalembert
import PhysJS.Eddington
import PhysJS.YangMills
import PhysJS.JohnsonNyquist
import PhysJS.Mond
import PhysJS.Einstein
import PhysJS.KibbleZurek
import PhysJS.HawkingUnruh
import PhysJS.Fret
import PhysJS.QuantumBounce
import PhysJS.Landauer
import PhysJS.Jarzynski
import PhysJS.Lindblad
import PhysJS.Jeans
import PhysJS.Deflection
import PhysJS.Sommerfeld
import PhysJS.ThermalDeBroglie
import PhysJS.Josephson
import PhysJS.QuantumHall
import PhysJS.Laughlin
import PhysJS.Kss
import PhysJS.PlanckArea
import PhysJS.Shapiro
