import PhysJS.KgSchrodinger
import PhysJS.KleinGordonWave
import PhysJS.StiffString
import PhysJS.TelegraphDiffusion
import PhysJS.TelegraphWave
import PhysJS.Pendulum
import PhysJS.KgOscillator
import PhysJS.OscillatorDictionary
import PhysJS.WaveDalembert
import PhysJS.Eddington
import PhysJS.YangMills
import PhysJS.JohnsonNyquist
import PhysJS.Mond
import PhysJS.Einstein
import PhysJS.VacuumFriedmann
import PhysJS.Dimensional
import PhysJS.Coarsening
import PhysJS.KibbleZurek
import PhysJS.HawkingUnruh
import PhysJS.Fret
import PhysJS.QuantumBounce
import PhysJS.Landauer
import PhysJS.Jarzynski
import PhysJS.Lindblad
import PhysJS.Jeans
import PhysJS.Deflection
import PhysJS.Sommerfeld
import PhysJS.ThermalDeBroglie
import PhysJS.Josephson
import PhysJS.QuantumHall
import PhysJS.Laughlin
import PhysJS.Kss
import PhysJS.PlanckArea
import PhysJS.Shapiro
import PhysJS.RandallSundrum
import PhysJS.EinsteinCartan
import PhysJS.EffectiveTemperature
import PhysJS.ToricCode
import PhysJS.QuantumCritical
import PhysJS.TimeSymmetric
import PhysJS.BornOverlap
import PhysJS.EntropyProduction
import PhysJS.CompositeHiggs
import PhysJS.Crossing
import PhysJS.Chandrasekhar
import PhysJS.Entanglement
import PhysJS.RadiationPressure
import PhysJS.AlfvenSpeed
import PhysJS.TolmanEhrenfest
import PhysJS.FastMagnetosonic
import PhysJS.EinsteinRelation
import PhysJS.Clapeyron
import PhysJS.GravitationalRedshift
import PhysJS.KelvinRelation
import PhysJS.MagneticPressure
import PhysJS.LondonPenetration
import PhysJS.PlasmaBeta
