import KgSchrodinger
import KleinGordonWave
import StiffString
import TelegraphDiffusion
import TelegraphWave
import Pendulum
import KgOscillator
import OscillatorDictionary
import WaveDalembert
import Eddington
import YangMills
import JohnsonNyquist
import Mond
import Einstein
import VacuumFriedmann
import Dimensional
import Coarsening
import KibbleZurek
import HawkingUnruh
import Fret
import QuantumBounce
import Landauer
import Jarzynski
import Lindblad
import Jeans
import Deflection
import Sommerfeld
import ThermalDeBroglie
import Josephson
import QuantumHall
import Laughlin
import Kss
import PlanckArea
import Shapiro
import RandallSundrum
import EinsteinCartan
import EffectiveTemperature
import ToricCode
import QuantumCritical
import TimeSymmetric
import BornOverlap
import EntropyProduction
import CompositeHiggs
import Crossing
import Chandrasekhar
import Entanglement
import RadiationPressure
import AlfvenSpeed
import TolmanEhrenfest
import FastMagnetosonic
import EinsteinRelation
import Clapeyron
import GravitationalRedshift
import KelvinRelation
